// This file is part of Compact.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import inspect from 'object-inspect';

/**
 * An error originating from code generated by the Compact compiler
 */
export class CompactError extends Error {
  readonly isCompactError = true;

  constructor(msg: string) {
    super(msg);
    this.name = 'CompactError';
  }
}

/**
 * Thrown when a cross-contract call targets a contract whose deployed verifier key for the
 * called circuit does not match the verifier key of the implementation the caller was compiled
 * against. Under the current model every `contract T` interface resolves to exactly one
 * implementation (its `T.compact`), and the caller's compiled bundle records that implementation's
 * verifier-key fingerprint (`expectedVk`). A mismatch means the address passed for the `T` argument
 * points at a different contract than the one the caller was linked to.
 */
export class ContractInterfaceMismatchError extends CompactError {
  constructor(
    readonly calleeAddress: string,
    readonly circuitId: string,
    readonly expectedVerifierKeyHash: string,
    readonly actualVerifierKeyHash: string,
  ) {
    super(
      `Cross-contract call to '${calleeAddress}': the contract deployed there does not match the ` +
        `implementation the caller was compiled against for circuit '${circuitId}'. Expected verifier ` +
        `key '${expectedVerifierKeyHash}', but the deployed contract's '${circuitId}' has verifier key ` +
        `'${actualVerifierKeyHash}'. The address likely points to a different contract than the one this ` +
        `interface resolves to.`,
    );
    this.name = 'ContractInterfaceMismatchError';
  }
}

/**
 * Compiler internal for assertions
 * @internal
 */
export function assert(b: boolean, s: string): void {
  if (!b) {
    const msg = `failed assert: ${s}`;
    throw new CompactError(msg);
  }
}

/**
 * Compiler internal for asserting an object is non-nullable.
 * @internal
 */
export function assertDefined<T>(t: T | undefined, name: string): asserts t is NonNullable<T> {
  if (t === undefined || t === null) {
    throw new CompactError(`Expected ${name} to be defined`);
  }
}

/**
 * Compiler internal for asserting an object is nullable.
 * @internal
 */
export function assertUndefined(t: any, name: string): void {
  if (t !== undefined && t !== null) {
    throw new CompactError(`Expected ${name} to be undefined`);
  }
}

/**
 * Compiler internal for type errors
 * @internal
 */
export function typeError(who: string, what: string, where: string, type: string, x: any): never {
  const msg = `type error: ${who} ${what} at ${where}; expected value of type ${type} but received ${inspect(x)}`;
  throw new CompactError(msg);
}
