// This file is part of Compact.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Common grammar to reuse with other grammars.
 */
const common = {
    end_line: [['valid_end_line'], ['invalid_start_or_end_line']],
    front_line: [['valid_end_line'], ['invalid_start_or_end_line'], ['line_separator']],
    valid_end_line: [[';'], [';\n']],
    line_separator: [['\n']],
    invalid_start_or_end_line: [
        [''],
        ['.\n'],
        ['!'],
        ['?'],
        [','],
        [':'],
        ['\n\n'],
        ['\/'],
        ['\//'],
        ['('],
        [')'],
        ['{'],
        ['}'],
        ['>'],
        ['<'],
        ['['],
        [']'],
        ['$'],
        ['&'],
        ['*'],
        ['='],
        ['_'],
        ['%'],
        ['@'],
        ['±'],
        ['§'],
        ['%s'],
        ['%c'],
        ['%d'],
        ['%h'],
        ['%i'],
        ['\t'],
    ],
    random_keyword: [['javascript_keywords'], ['compact_keywords'], ['other_keywords']],
    javascript_keywords: [
        'abstract',
        'arguments',
        'await',
        'boolean',
        'break',
        'byte',
        'case',
        'catch',
        'char',
        'class',
        'const',
        'continue',
        'debugger',
        'default',
        'delete',
        'do',
        'double',
        'else',
        'enum',
        'eval',
        'export',
        'extends',
        'false',
        'final',
        'finally',
        'float',
        'for',
        'function',
        'goto',
        'if',
        'implements',
        'import',
        'in',
        'instanceof',
        'int',
        'interface',
        'let',
        'long',
        'native',
        'new',
        'null',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'short',
        'static',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'true',
        'try',
        'typeof',
        'var',
        'void',
        'volatile',
        'while',
        'with',
        'yield',
        'Array',
        'Date',
        'hasOwnProperty',
        'Infinity',
        'isFinite',
        'isNaN',
        'isPrototypeOf',
        'length',
        'Math',
        'NaN',
        'name',
        'Number',
        'Object',
        'prototype',
        'String',
        'toString',
        'undefined',
        'valueOf',
    ],
    compact_keywords: [
        'false',
        'true',
        'export',
        'from',
        'import',
        'module',
        'prefix',
        'as',
        'assert',
        'circuit',
        'const',
        'constructor',
        'contract',
        'default',
        'disclose',
        'else',
        'enum',
        'fold',
        'for',
        'if',
        'include',
        'ledger',
        'map',
        'new',
        'of',
        'pad',
        'pragma',
        'pure',
        'return',
        'sealed',
        'slice',
        'struct',
        'type',
        'witness',
        'Boolean',
        'Bytes',
        'Field',
        'Opaque',
        'Uint',
        'Vector',
        'arguments',
        'await',
        'break',
        'case',
        'catch',
        'class',
        'continue',
        'debugger',
        'delete',
        'do',
        'eval',
        'event',
        'extends',
        'finally',
        'function',
        'implements',
        'in',
        'instanceof',
        'interface',
        'let',
        'log',
        'null',
        'package',
        'private',
        'protected',
        'public',
        'static',
        'super',
        'switch',
        'this',
        'throw',
        'try',
        'typeof',
        'var',
        'void',
        'while',
        'with',
        'yield',
    ],
    other_keywords: ['self', 'https://', 'file://', 'ftp://', 'define', 'lambda'],
    compact_types: [
        ['valid_types'],
        ['valid_types', ' as ', 'valid_types'],
        ['valid_types', ' as ', 'invalid_types'],
        ['invalid_types'],
        ['invalid_types', ' as ', 'invalid_types'],
        ['invalid_types', ' as ', 'valid_types'],
    ],
    contaminated_compact_types: [
        ['compact_types'],
        ['random_string'],
        ['random_keyword'],
        ['random_number'],
        ['random_version'],
        ['random_table'],
    ],
    valid_types: [['valid_std_types'], ['valid_ledger_types']],
    invalid_types: [['invalid_std_types'], ['invalid_ledger_types']],
    valid_std_types: [
        ['Boolean'],
        ['Field'],
        ['Uint<', 'random_number', '>'],
        ['Uint<', 'random_number', '..', 'random_number', '>'],
        ['Opaque<"string">'],
        ['Opaque<"Uint8Array">'],
        ['Bytes<', 'random_number', '>'],
        ['Vector<', 'random_number', ', ', 'valid_std_types', '>'],
        ['Maybe<', 'valid_std_types', '>'],
        ['Either<', 'valid_std_types', ',', 'valid_std_types', '>'],
        ['JubjubPoint'],
        ['MerkleTreeDigest'],
        ['MerkleTreePathEntry'],
        ['MerkleTreePath<', 'random_number', ',', 'valid_std_types', '>'],
        ['ContractAddress'],
        ['ShieldedCoinInfo'],
        ['QualifiedShieldedCoinInfo'],
        ['ZswapCoinPublicKey'],
        ['ShieldedSendResult'],
        ['UserAddress'],
        ['[]'],
    ],
    invalid_std_types: [
        ['Uint<', 'random_string', '>'],
        ['Bytes<', 'random_string', '>'],
        ['Bytes<', 'random_string', '..', 'random_string', '>'],
        ['Bytes<', 'compact_types', '..', 'compact_types', '>'],
        ['Opaque<', 'random_number', '>'],
        ['Opaque<', 'random_string', '>'],
        ['Opaque<', 'compact_types', '>'],
        ['Vector<', 'random_number', ', ', 'invalid_types', '>'],
        ['Vector<', 'random_string', ', ', 'invalid_types', '>'],
        ['Vector<', 'random_number', ', ', 'valid_std_types', '>'],
        ['Maybe<', 'compact_types', '>'],
        ['Either<', 'compact_types', ',', 'compact_types', '>'],
        ['MerkleTreePath<', 'random_number', ',', 'compact_types', '>'],
    ],
    valid_ledger_types: [
        ['Kernel'],
        ['Counter'],
        ['List<', 'valid_std_types', '>'],
        ['Set<', 'valid_std_types', '>'],
        ['Map<', 'valid_types', ', ', 'valid_std_types', '>'],
        ['MerkleTree<', 'random_number', ', ', 'valid_std_types', '>'],
        ['HistoricMerkleTree<', 'random_number', ', ', 'valid_std_types', '>'],
    ],
    invalid_ledger_types: [
        ['Cell<', 'random_number', '>'],
        ['Cell<', 'compact_types', ', ', 'compact_types', '>'],
        ['Set<', 'random_number', '>'],
        ['Set<', 'compact_types', '>'],
        ['Set<', 'compact_types', ', ', 'compact_types', '>'],
        ['Map<', 'random_number', '>'],
        ['Map<', 'compact_types', '>'],
        ['Map<', 'random_number', 'compact_types', '>'],
        ['List<', 'random_number', '>'],
        ['List<', 'compact_types', '>'],
        ['List<', 'compact_types', ', ', 'compact_types', '>'],
        ['MerkleTree<', 'random_number', '>'],
        ['MerkleTree<', 'compact_types', ', ', 'compact_types', '>'],
        ['MerkleTree<', 'random_number', ', ', 'compact_types', '>'],
        ['HistoricMerkleTree<', 'compact_types', '>'],
        ['HistoricMerkleTree<', 'compact_types', ', ', 'compact_types', '>'],
        ['HistoricMerkleTree<', 'random_number', ', ', 'compact_types', '>'],
    ],
    random_operator: [['valid_operator'], ['invalid_operator']],
    valid_operator: [
        [' > '],
        [' < '],
        [' = '],
        [' ! '],
        [' * '],
        [' / '],
        [' + '],
        [' - '],
        [' || '],
        [' && '],
        [' <= '],
        [' >= '],
        [' != '],
        [' == '],
    ],
    invalid_operator: [
        [''],
        [' '],
        ['\n'],
        [' . '],
        [' ` '],
        [' # '],
        [' ± '],
        [' § '],
        [' , '],
        [' : '],
        [' ; '],
        [' [ '],
        [' ] '],
        [' { '],
        [' } '],
        [' ( '],
        [' ) '],
        [' % '],
        [' & '],
        [' ? '],
        ['   '],
        [' ~ '],
        [" ' "],
        [' " '],
        [' \\'],
        [' ^ '],
        [' | '],
        [' := '],
        [' |= '],
        [' /= '],
        [' %= '],
        [' &= '],
        [' ^= '],
        [' &! '],
        [' !! '],
        [' ** '],
        [' !* '],
        [' !> '],
        [' <! '],
        [' >> '],
        [' << '],
        [' >< '],
        [' <> '],
        [' => '],
        [' =< '],
        [' [] '],
        [' {} '],
        [' () '],
        [' ,, '],
        [' ;; '],
        [' :: '],
        [' ;: '],
        [' :; '],
        [' ?: '],
        [' %s '],
        [' .. '],
        [' __ '],
        [' ~= '],
        [' ±= '],
        [' <~ '],
        [' =! '],
        [' += '],
        [' *= '],
        [' -= '],
        [' =+ '],
        [' =* '],
        [' =- '],
        [' ++ '],
        [' -- '],
        [' === '],
        [' >>> '],
        [' <<< '],
        [' <<= '],
        [' >>= '],
    ],
};

exports.common = common;
